import React from 'react';

export const Insights: React.FC = () => {
  return (
    <div className="panel" style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      <div>
        <h2 style={{ fontSize: '18px', fontWeight: 600 }}>Coach & Front Office Insights</h2>
        <p style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
          Actionable basketball strategy and player scouting intelligence generated by the spatial engine
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        
        {/* Insight 1 */}
        <div className="insight-item">
          <div className="insight-icon">🎯</div>
          <div className="insight-content">
            <h4 className="insight-title">The Curry Effect: Gravity & Shot-Making</h4>
            <p className="insight-desc">
              Stephen Curry is the ultimate statistical outlier. Our model shows his average shot difficulty (Expected eFG%) is a standard <strong>50.2%</strong>. 
              However, his actual eFG% is <strong>55.5%</strong>, yielding a <strong>+5.3% Shot-Making Delta</strong>. 
              Curry breaks typical offensive models because his pull-up three-pointers from 28+ feet are more efficient than average league layups, forcing defensive structures to stretch beyond traditional limits.
            </p>
          </div>
        </div>

        {/* Insight 2 */}
        <div className="insight-item">
          <div className="insight-icon">🛡️</div>
          <div className="insight-content">
            <h4 className="insight-title">Defensive Specialization vs. Scheme Design</h4>
            <p className="insight-desc">
              Coaches must match scheme to personnel. Rudy Gobert holds a <strong>+12.0% paint contest impact</strong>, making him an elite drop-coverage center. 
              In contrast, Alex Caruso holds a <strong>+8.0% perimeter impact</strong>, making him the ideal switch/hedge defender. 
              Our model proves that Caruso's impact comes from <em>suppressing openness</em> (reducing average defender distance to 3.4ft), whereas Gobert's impact comes from <em>spatial deterrence</em> (forcing shooters to alter release angles inside).
            </p>
          </div>
        </div>

        {/* Insight 3 */}
        <div className="insight-item">
          <div className="insight-icon">📊</div>
          <div className="insight-content">
            <h4 className="insight-title">Giannis: Shot Selection is King</h4>
            <p className="insight-desc">
              Giannis Antetokounmpo generates the highest **Average Shot Quality (Expected eFG% of 59.5%)** in our database. 
              By taking 75% of his shots in the Restricted Area, he maximizes baseline math. 
              Even if a player is a below-average shooter, they can reach elite efficiency through optimized spatial shot selection.
            </p>
          </div>
        </div>

        {/* Insight 4 */}
        <div className="insight-item">
          <div className="insight-icon">💡</div>
          <div className="insight-content">
            <h4 className="insight-title">KD: The Death of the "Mid-Range is Bad" Myth</h4>
            <p className="insight-desc">
              Standard analytics says the mid-range (4-22 ft) is a low-value zone because it yields fewer expected points than at-the-rim or 3-point looks. 
              But Kevin Durant shoots <strong>+12.0% above expected</strong> from mid-range. 
              For elite shot-makers, mid-range pull-ups are high-quality offense, especially in playoff half-court sets when defenses take away layups and open threes.
            </p>
          </div>
        </div>
        
      </div>

      {/* Analytical Glossary */}
      <div style={{ borderTop: '1px solid var(--panel-border)', paddingTop: '20px' }}>
        <h3 style={{ fontSize: '14px', marginBottom: '12px' }}>Operational Glossary</h3>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '12px' }}>
          <div style={{ background: 'rgba(0,0,0,0.2)', padding: '12px', borderRadius: '8px', border: '1px solid var(--panel-border)' }}>
            <strong style={{ color: 'var(--color-primary)', fontSize: '13px' }}>xeFG% (Expected eFG%)</strong>
            <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: '1.4' }}>
              Calculates the probability of a shot going in based on context (distance, defender distance, dribbles, catch vs pull-up) multiplied by its point value. 
              It represents what a league-average shooter would shoot given those exact spatial circumstances.
            </p>
          </div>
          <div style={{ background: 'rgba(0,0,0,0.2)', padding: '12px', borderRadius: '8px', border: '1px solid var(--panel-border)' }}>
            <strong style={{ color: 'var(--color-primary)', fontSize: '13px' }}>Shot-Making Delta (eFG% - xeFG%)</strong>
            <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: '1.4' }}>
              Isolates the shooter's individual skill from the quality of the shot they took. 
              A positive value shows the player makes "difficult" shots, while a negative value shows they miss shots the average player would make.
            </p>
          </div>
          <div style={{ background: 'rgba(0,0,0,0.2)', padding: '12px', borderRadius: '8px', border: '1px solid var(--panel-border)' }}>
            <strong style={{ color: 'var(--color-primary)', fontSize: '13px' }}>Defensive Shot Quality Allowed (dSQA)</strong>
            <p style={{ fontSize: '11px', color: 'var(--text-secondary)', marginTop: '4px', lineHeight: '1.4' }}>
              Measures defender proximity control and rim deterrence. 
              A defender with a high positive impact makes shooters uncomfortable, forcing them into lower-than-average conversion percentages.
            </p>
          </div>
        </div>
      </div>
      
      {/* Front Office Pitch */}
      <div style={{ background: 'linear-gradient(135deg, rgba(127, 0, 255, 0.1) 0%, rgba(0, 242, 254, 0.1) 100%)', border: '1px solid rgba(0, 242, 254, 0.2)', padding: '16px', borderRadius: '12px', marginTop: '8px' }}>
        <h4 style={{ fontSize: '13px', fontWeight: 600, color: '#fff', marginBottom: '6px' }}>
          🚀 Actionable Front Office Impact
        </h4>
        <p style={{ fontSize: '12px', color: 'var(--text-secondary)', lineHeight: '1.5' }}>
          <strong>Contract Valuations:</strong> Buy low on players with high Shot Quality (xeFG%) but poor recent conversion, as shooting efficiency is highly mean-reverting.
          <br />
          <strong>Scouting & Recruiting:</strong> Identify defenders who post high defensive impacts even in bad team defensive systems. dSQA separates individual contest capability from team defensive help.
        </p>
      </div>
    </div>
  );
};
